#!/usr/bin/env bash

# Commented out until I figure out how to handle Github API key so this can be automated
#./setup_scripts/set_up_ssh.sh

./setup_scripts/config_setup.sh
./setup_scripts/repo-setup.sh
