#!/bin/bash

KATELLO_PATH=~/katello

if [[ -n $1 ]]
then
  RAKE_PATH=`bundle show rake`
  mode=all ruby -I"lib:test:${KATELLO_PATH}/test:${KATELLO_PATH}/spec" -I"${RAKE_PATH}/lib" \
    "${RAKE_PATH}/lib/rake/rake_test_loader.rb" $@
else
  bundle exec rake test:katello
fi

